### ISSUE TITLE
Compilation troubles using Visual Studio 2015 64bit

### ISSUE THREAD

**Issue by Mr-Question** [rballester/tthresh#1]
Hi!

Thank you for this project, it seems very perspective.

I am trying to evaluate functionality provided by tthresh.
I can compile it on Linux without any problem, but my aim is Windows platform and I have got a bunch of compilation errors there.

So, I will appreciate very well for any help to make it working on this OS.

Here is my way:

**zlib_io.hpp:**
Cannot open include file: 'zlib.h': No such file or directory

When I change CMakeLists.txt from set(ZLIB_INCLUDE_DIRS zlib ${ZLIB_BINARY_DIR}) to set(ZLIB_INCLUDE_DIRS external/zlib ${ZLIB_BINARY_DIR}), I can go further.

**compress.hpp:**
Cannot open include file: 'unistd.h': No such file or directory

I have made the following modification with success:
#ifdef WIN32
#include <io.h>
#else
#include <unistd.h>
#endif

After that I stuck with "and", "or" and "not" operators unsupported by VS compiler.

The following definitions in CMakeLists.txt helped:
add_definitions (-Dand=&& -Dor=|| -Dnot=!)

**tucker.hpp:**
'M_PI': undeclared identifier

Solved by:
#define _USE_MATH_DEFINES
#include <math.h>

Later, there are several errors of similar nature fixed by change to int64_t type in **compress.hpp:**
'i': index variable in OpenMP 'for' statement must have signed integral type

Then compiler refused to build **zlib_io.hpp** due to string passed to SET_BINARY_MODE instead of FILE*:
'int fileno(FILE *)': cannot convert argument 1 from 'const char *' to 'FILE *'

Solution:
Comment out all lines with SET_BINARY_MODE and add "b" key to each call of fopen function in file.

And finally I have got working app!
But during compression procedure it hunged completely...

The matter was in infinite loop in **encode.hpp** when value of "high" variable is turned to null as far as MAX_CODE is equal to 0.

I have tried to fix it like this:
uint64_t MAX_CODE = (static_cast<uint64_t>(1)<<CODE_VALUE_BITS)-1;

After that compressing process finishes correctly, but I am unable to decompress data to initial state after all...

There are two files in attachments containing entire output which I have got during compression/decompression using the following commands (I use BostonTeapot.raw from tc18.org for experiments):
**tthresh -i BostonTeapot.raw -c BostonTeapot.raw_comp -t uchar -s 256 256 178 -p 0 -d**

**tthresh -o BostonTeapot.raw_unc -c BostonTeapot.raw_comp -d**

[compress.txt](https://github.com/rballester/tthresh/files/2213357/compress.txt)
[decompress.txt](https://github.com/rballester/tthresh/files/2213358/decompress.txt)

Best regards.

**Comment by rballester** [comment]
The last few commits by @shamanDevel should have fixed the remaining Windows-related issues. Can you confirm whether it works on your compiler now?
