### ISSUE TITLE
input file format

### ISSUE THREAD

**Issue by ldv1** [rballester/tthresh#3]
what is the input file format expected by tthresh ?
thanks

**Comment by rballester** [comment]
Hi ldv1, tthresh expects files in raw format (that is, an array of binary values, without any headers) in FORTRAN ordering (first dimension varies the fastest). As an example, you can check "3D_sphere_64_uchar.raw" in the tthresh/data/ folder of this very repository.

If your file has a header that you want to skip, you may do so via the flag -k (see the flag -h for more info).
