### ISSUE TITLE
Compilation fails using AppleClang

### ISSUE THREAD

**Issue by lindstro** [rballester/tthresh#4]
TTHRESH won't build on a Mac using AppleClang 11.0.0.11000033.  The compiler complains about missing __float128 and __float80, which I believe are gcc extensions.

**Comment by jpcoding** [comment]
Tried to use g++-11 on Apple M1 chip. Got the same error message. missing  __float128 and __float80. 
cmake log  as follows 
-- The CXX compiler identification is GNU 11.2.0
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Configuring done
-- Generating done
